services:
    form.serializer_normalizer.form_error:
        class: Symftony\FormHandler\FormBundle\Serializer\Normalizer\FormInvalidNormalizer
        arguments:
            - '@translator'
        public: false
        tags:
            - { name: 'serializer.normalizer' }

    form.form_handler.form:
        class: Symftony\FormHandler\FormHandler
        tags:
            - { name: 'form.handler' }

    form.type_extension.handler_options:
        class: Symftony\FormHandler\FormHandlerOptionsTypeExtension
        tags:
            - { name: 'form.type_extension', extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }

